export const refs = {
    togler: document.querySelector('.theme__togler'),
    mobileToggler: document.querySelector('.theme-mobile__togler'),
    tabs: document.querySelector('.authorization__box'),
    authorizationModal: document.querySelector('.backdrop'),
    authorizationSubmit: document.querySelector('.authorization__submit'),
    authorizationCancel: document.querySelector('.authorization__cancel'),
    authorizationForm: document.querySelector('.authorization__form'),
    regBtn: document.querySelector('.authorization__btn--reg'),
    logBtn: document.querySelector('.authorization__btn--log'),
    checkBoxMessage: document.querySelector(
        '.authorization__checkbox--message'
    ),
    confirmPass: document.querySelector('.authorization__field--confirm'),
    newsContainer: document.querySelector('.news'),
    favoritesListBtn: document.getElementById('#favoritesList'),
    categoriesBtns: document.querySelector('.home__category'),
    categoriesDropdown: document.querySelector('.home__dropdown-menu'),
    categoryButton: document.querySelector('.home__category-button'),
    openIcon: document.querySelector('.home__category-button-icon--open'),
    closeIcon: document.querySelector('.home__category-button-icon--close'),
    pg: document.getElementById('pagination'),
    pgContainer: document.querySelector('.pagination__container'),
    btnNextPg: document.querySelector('.pagination__next-page'),
    btnPrevPg: document.querySelector('.pagination__prev-page'),
    boxItems: document.querySelector('.read'),
    gridBox: document.querySelector('.grid-box'),
    form: document.querySelector('.search-form'),
    dateInput: document.querySelector('#datetime-picker'),
    newsSection: document.querySelector('.news-section'),
    newsNotFoundSection: document.querySelector('.not-found-section'),
    seachQuery: document.querySelector('.header__input-search'),
};
